## K Nearest Neighbors - KNN Python Lecture

Hi Guys,<br>

Welcome to the K Nearest Neighbors with Python lecture. <br>

After the theory lecture, its time to learn by doing. <br>
Let's create a situation here, this time you got the data which is highly confidential! <br>
Your client does not want to disclose the hidden features (dimensions). All the features are coded with some numbers. So far, based on the combination of different feature's code, your client makes the decisions.<br>
Data is growing and your client wants to automate the process. You are give a task to use the coded data along with the target class in 'Results' column and help your client in decision making. <br>
You decide to go with the KNN and create a model that predicts the target class for the new customers. <br>
**Great, let's explore!**<br>

First thing first, let's imports the libraries that we need!

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#%matplotlib inline

# Lines below are just to ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("Coded_Data.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'Coded_Data.csv'

In our dataframe, the first column looks like the index, let's set `index_col = 0`

In [5]:
df = df.drop('Unnamed: 0',axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [7]:
df

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

Great, this looks fine now!<br>

Let's overview the data, we can use `info()` here!

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cd_1    1000 non-null   float64
 1   Cd_2    1000 non-null   float64
 2   Cd_3    1000 non-null   float64
 3   Cd_4    1000 non-null   float64
 4   Cd_5    1000 non-null   float64
 5   Cd_6    1000 non-null   float64
 6   Cd_7    1000 non-null   float64
 7   Cd_8    1000 non-null   float64
 8   Cd_9    1000 non-null   float64
 9   Cd_10   1000 non-null   float64
 10  Result  1000 non-null   object
dtypes: float64(10), object(1)
memory usage: 86.1+ KB

Let's split the data so that we can fit the `scaler` to the features only!

In [9]:
#features and results/target
target = df['Result']
features = df.drop('Result',axis=1)

In [12]:
features

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1

[1000 rows x 10 columns]

In [13]:
target

0      Y
1      N
2      N
3      Y
4      Y
      ..
995    Y
996    N
997    Y
998    Y
999    Y
Name: Result, Length: 1000, dtype: object

Let's fit `scaler` to the features now!

In [14]:
# Importing
from sklearn.preprocessing import StandardScaler
# Creating instance 'scaler'
scaler = StandardScaler()

In [15]:
# We can do this in a one line as well!
#scaler.fit(df.drop('Result',axis=1))
scaler.fit(features)

StandardScaler()

So, we have the fitted features to the `scaler` object. We will use this `scaler` object to transform all the features using `.transform()` method in `Scikit-learn` to do the `standardization` job by centering and scaling.<br>
Let's pass the features to `scaler.transform()` to get standardized features in `scaled_features`!

In [16]:
scaled_features = scaler.transform(features)

In [18]:
scaled_features

array([[-0.12252539,  0.1875694 , -0.91183199, ..., -1.48006982,
        -0.95256187, -0.64536551],
       [-1.08602779, -0.43340316, -1.02415132, ..., -0.20055606,
        -1.82621843,  0.6351032 ],
       [-0.78865051,  0.33745933,  0.30003449, ...,  0.28776079,
        -0.68275617, -0.3762815 ],
       ...,
       [ 0.64470801, -0.51191693, -0.17880055, ..., -2.36398512,
        -0.81123508,  0.11549271],
       [ 0.46628164, -0.98299956, -1.46751711, ..., -0.03984418,
         0.40289057, -0.85877696],
       [-0.39016495, -0.59756832, -1.43204784, ..., -0.56524838,
         0.33865112,  0.01342636]])

`scaled_features` is a NumPy array, Let's convert this into the pandas `DataFrame`!<br>
We can use our `df.columns` to get the columns name and pass that to `DatFrame()` along with `scaled_features`, note we don't need `Results` column, [:-1] will work *(everything but the last one)*!

In [19]:
#Before Scaling
df

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

In [20]:
cols = df.columns[:-1]
cols

Index(['Cd_1', 'Cd_2', 'Cd_3', 'Cd_4', 'Cd_5', 'Cd_6', 'Cd_7', 'Cd_8', 'Cd_9',
       'Cd_10'],
      dtype='object')

In [22]:
#After Scaling
df_scaled_features = pd.DataFrame(data=scaled_features, columns=cols)#df.columns[:-1])
df_scaled_features

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
0,-0.122525,0.187569,-0.911832,0.318653,-1.035516,-2.305940,-0.801865,-1.480070,-0.952562,-0.645366
1,-1.086028,-0.433403,-1.024151,0.624941,-0.445471,-1.153296,-1.131088,-0.200556,-1.826218,0.635103
2,-0.788651,0.337459,0.300034,0.753154,2.030007,-0.873275,2.597862,0.287761,-0.682756,-0.376282
3,0.983718,1.058359,-0.622166,0.624941,0.449771,-0.267648,1.751290,1.066595,1.244427,-1.025795
4,1.138354,-0.640394,-0.710839,-0.058864,0.822788,-0.938396,0.595651,-1.473889,1.038861,0.273232
...,...,...,...,...,...,...,...,...,...,...
995,0.210537,-0.312064,0.063573,-0.258307,0.015714,-1.394244,-0.848897,-2.605053,-0.136721,-0.070082
996,-1.294192,-0.618981,0.370973,0.482481,1.568822,1.275723,0.360492,-1.239002,-0.682756,1.470191
997,0.644708,-0.511917,-0.178801,1.023827,-0.540420,-0.228575,-2.259851,-2.363985,-0.811235,0.115493
998,0.466282,-0.983000,-1.467517,-0.073110,2.369113,-0.000651,-0.418892,-0.039844,0.402891,-0.858777
999,-0.390165,-0.597568,-1.432048,0.510973,-0.404778,-2.025919,-0.727958,-0.565248,0.338651,0.013426

<br>Our data is ready for the Machine Learning part now!
## Let's do the train_test split 
I am sure, you are very comfortable with this now!

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X = df_scaled_features
y = target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)  #, random_state=2

In [25]:
X_train

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
468,-0.681595,-1.518321,0.087219,-0.165709,-0.676063,-0.423939,-1.278902,-2.431979,0.640577,-1.053631
370,-1.490461,1.872047,0.512850,0.211809,-0.730320,1.842278,0.629245,-1.115377,-1.415086,-1.471175
104,-0.140368,0.387423,-1.059621,0.845752,-2.269864,-0.020188,0.736747,0.584460,1.353634,-0.784547
943,-0.265266,-0.233550,0.051750,-0.023249,-0.411560,-0.463011,-0.338266,-0.484892,-0.669908,2.602200
82,0.549547,-0.454816,-1.834033,-0.585964,0.938084,-1.250977,-0.808584,-0.676510,-0.329439,-1.396945
...,...,...,...,...,...,...,...,...,...,...
168,0.739869,0.415973,-1.030063,-1.162924,-1.523829,0.429148,-0.983274,-0.243825,0.075269,0.004148
549,-0.622119,1.943423,1.825213,-0.187078,0.612542,-0.313233,-0.754834,1.004783,-0.766267,-0.506184
959,-0.509116,0.244670,0.087219,-0.251184,-0.621806,1.471087,-0.271078,2.395559,-0.181688,-0.728874
675,-0.532906,0.159019,0.004457,-1.383736,1.100855,-0.710472,-0.297953,-0.719779,-0.740572,0.996975
440,-0.717280,0.016267,0.294123,-0.265430,1.779068,0.292394,-1.984379,-0.027482,-1.010377,0.597988

In [26]:
y_train

468    Y
370    N
104    Y
943    N
82     Y
      ..
168    Y
549    N
959    N
675    N
440    N
Name: Result, Length: 700, dtype: object

## KNN
Our focus is to come up with a model that can predict the class in `Result` for the new data point. We don't know what k number will work best, let's start with k = 1 at the moment. <br>
We need to import the `KNeighborsClassifier` from `sklearn.neighbors`.

In [27]:
from sklearn.neighbors import KNeighborsClassifier

Let's Create a KNN model instance with n_neighbors=1

In [28]:
knn = KNeighborsClassifier(n_neighbors=3) 
#shift+tab to see the other options, we will only use n_neighbors

Let's fit this model to the training data, You know this all now!

In [33]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Let's do the predictions now!

In [34]:
predictions = knn.predict(X_test)
predictions

array(['Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y',
       'N', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N',
       'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N',
       'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'N', 'N',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y',
       'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N',
       'Y'], dtype=object)

In [35]:
knn.score(X_test, y_test)

0.91

In [37]:
knn.predict([[-1.122525, 0.287569, -0.911832, -0.318653, -0.035516, -0.105940, -0.801865, -1.480070, -0.952562, 2.645366]])

array(['N'], dtype=object)

## Evaluation
As we already know, the evaluation is very important to know if the model is working fine or not! <br>
Let's see how the confusion matrix and classification report look like!

In [38]:
from sklearn.metrics import classification_report,confusion_matrix

In [39]:

print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           N       0.88      0.90      0.89       122
           Y       0.93      0.92      0.92       178

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300

So, it was worth finding the optimum value for k, our model is performing better. 
## Great Job!
Let's move on to the project exercise now to practice the skills in knn!